#!/bin/sh
BASEDIR=$(dirname $0)
wget http://api.muc.ccc.de/nextevent.json -O $BASEDIR/nextevent.raw
if [ -s $BASEDIR/nextevent.raw ] ; then
	< $BASEDIR/nextevent.raw json_pp > $BASEDIR/nextevent.json
else
	echo "Kalenderscraper failed."
fi
