#!/bin/sh
BASEDIR=$(dirname $0)
$BASEDIR/space_state/update
python $BASEDIR/mvgdefas/getmvglive.py
python $BASEDIR/mvgdefas/ticker/getmvgticker.py
$BASEDIR/drinkleaker/update
python $BASEDIR/timetoflip/clock.py
python $BASEDIR/kalenderscraper/kalenderscraper.py
