#!/bin/sh
BASEDIR=$(dirname $0)
[ -d  $BASEDIR/space_state ] && $BASEDIR/space_state/update
[ -d $BASEDIR/mvgdefas ] && python $BASEDIR/mvgdefas/getmvglive.py >/dev/null
[ -d $BASEDIR/mvgdefas ] && python $BASEDIR/mvgdefas/ticker/getmvgticker.py
[ -d $BASEDIR/drinkleaker ] && $BASEDIR/drinkleaker/update
$BASEDIR/kalenderscraper/update
$BASEDIR/ffmuc_state/update
