#!/bin/sh
BASEDIR=$(dirname $0)
curl https://ffmuc.net/data/nodes.json | python -c 'import sys, json; c = map(lambda n: n["statistics"]["clients"], filter(lambda n: n["flags"]["online"], json.loads(sys.stdin.read())["nodes"].values())); print "%s %s" % (len(c), sum(c))' > /tmp/node_stats
copy /tmp/node_stats $BASEDIR/node_stats
